version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=app.db 